export const MAP_VECTOR_TILE_LAYER_NAME = 'records';

export const MAP_VECTOR_TILE_EXTENT = 4096;

export const MAP_VECTOR_TILE_BUFFER = 64;

export const MAP_VECTOR_TILE_MAX_FEATURES = 50_000;

export const MAP_VECTOR_TILE_SIMPLIFICATION_MAX_ZOOM = 12;

export const WEB_MERCATOR_WORLD_WIDTH_METERS = 40_075_016.68557849;
